language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script: 
  - pear install pear/PHP_CodeSniffer
  - composer install -n
  - phpenv rehash

script: 
  - phpunit -c Tests/
  - phpcs --standard=PSR2 --extensions=php --ignore=vendor .
